# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio', models.CharField(max_length=200)),
                ('tipo_vehiculo', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(max_length=200)),
            ],
        ),
    ]
